import Input from "../../Atoms/Input";
import Section from "../../Atoms/Section";
import SectionGroup from "../../Atoms/SectionGroup";

export default function ParteDemandada({ data, onChange }) {
  return (
    <Section title="Parte Demandada">
      <SectionGroup>
        <Input
          label="Nombre"
          value={data.nombre}
          name="demandado_nombre"
          onChange={onChange}
        ></Input>
        <Input
          label="Apellido"
          value={data.apellido}
          name="demandado_apellido"
          onChange={onChange}
        ></Input>
        <Input
          label="DNI"
          type="number"
          value={data.documento}
          name="demandado_documento"
          onChange={onChange}
        ></Input>
        <Input
          label="Nacionalidad"
          value={data.nacionalidad}
          name="demandado_nacionalidad"
          onChange={onChange}
        ></Input>
      </SectionGroup>
      <SectionGroup>
        <Input
          label="Domicilio"
          value={data.domicilio}
          name="demandado_domicilio"
          onChange={onChange}
        ></Input>
      </SectionGroup>
      <SectionGroup>
        <Input
          label="Localidad"
          value={data.localidad}
          name="demandado_localidad"
          onChange={onChange}
        ></Input>
        <Input
          label="Partido"
          value={data.partido}
          name="demandado_partido"
          onChange={onChange}
        ></Input>
        <Input
          label="Provincia"
          value={data.provincia}
          name="demandado_provincia"
          onChange={onChange}
        ></Input>
      </SectionGroup>
      <SectionGroup>
        <Input
          label="Entrecalle"
          value={data.entrecalle}
          name="demandado_entrecalle"
          onChange={onChange}
        ></Input>
      </SectionGroup>
      <SectionGroup>
        <Input
          label="Codigo de país"
          type="number"
          value={data.codigoPais}
          name="demandado_codigoPais"
          onChange={onChange}
        ></Input>
        <Input
          label="Código de área"
          type="number"
          value={data.codigoArea}
          name="demandado_codigoArea"
          onChange={onChange}
        ></Input>
        <Input
          label="Teléfono"
          type="number"
          value={data.telefono}
          name="demandado_telefono"
          onChange={onChange}
        ></Input>
        <Input
          label="Fijo"
          value={data.telefonoFijo}
          name="demandado_telefonoFijo"
          onChange={onChange}
        ></Input>
      </SectionGroup>
    </Section>
  );
}
